"""
Database module exports.
"""

from .base import Base, TimestampMixin, SoftDeleteMixin, AuditMixin, generate_uuid
from .engine import engine, async_engine, get_engine, get_async_engine
from .session import SessionLocal, AsyncSessionLocal, get_db, get_async_db
from .init_db import init_db, create_tables, drop_tables, reset_db
from .repositories import BaseRepository

# Import all models
from .models import (
    User,
    UserSession,
    UserPreferences,
    Wallet,
    Transaction,
    Article,
    ArticleVersion,
    Incident,
    IncidentImage,
    IncidentVerification,
    Topic,
    Comment,
    Vote,
    Feedback,
    Notification,
    Subscription,
    Prediction,
    Dataset,
    Embedding,
    Image,
    Briefing,
    AuditLog,
    APIKey,
    # Add missing models based on previous files
    Organization,
    OrganizationMember,
    Team,
    TeamMember,
    OrganizationInvitation,
    OrganizationRole,
    OrganizationSettings,
    OrganizationAuditLog,
    TeamProject,
    PaymentMethod,
    Invoice,
    Payment,
    Discount,
    UsageRecord,
    BillingAlert,
    Model,
    FeatureSet,
    ModelVersion,
    PredictionBatch,
    ModelMonitoring,
    TopicAlias,
    TopicRelationship,
    ContentTopic,
    UserTopicInterest,
    TopicCluster,
    TopicClusterMember,
    TopicTrend,
    TopicExtractionJob,
    Poll,
    PollVote,
    VoteAggregate,
    UserReputation,
    VoteFraudDetection,
    Currency,
    WalletBalance,
    WalletSignature,
    WalletBackupKey,
    StakingPool,
    Staking,
    ExchangeRate,
)

__all__ = [
    # Base
    'Base',
    'TimestampMixin',
    'SoftDeleteMixin',
    'AuditMixin',
    'generate_uuid',
    
    # Engine
    'engine',
    'async_engine',
    'get_engine',
    'get_async_engine',
    
    # Session
    'SessionLocal',
    'AsyncSessionLocal',
    'get_db',
    'get_async_db',
    
    # Initialization
    'init_db',
    'create_tables',
    'drop_tables',
    'reset_db',
    
    # Repository
    'BaseRepository',
    
    # Models
    'User',
    'UserSession',
    'UserPreferences',
    'Wallet',
    'Transaction',
    'Article',
    'ArticleVersion',
    'Incident',
    'IncidentImage',
    'IncidentVerification',
    'Topic',
    'Comment',
    'Vote',
    'Feedback',
    'Notification',
    'Subscription',
    'Prediction',
    'Dataset',
    'Embedding',
    'Image',
    'Briefing',
    'AuditLog',
    'APIKey',
    # New models
    'Organization',
    'OrganizationMember',
    'Team',
    'TeamMember',
    'OrganizationInvitation',
    'OrganizationRole',
    'OrganizationSettings',
    'OrganizationAuditLog',
    'TeamProject',
    'PaymentMethod',
    'Invoice',
    'Payment',
    'Discount',
    'UsageRecord',
    'BillingAlert',
    'Model',
    'FeatureSet',
    'ModelVersion',
    'PredictionBatch',
    'ModelMonitoring',
    'TopicAlias',
    'TopicRelationship',
    'ContentTopic',
    'UserTopicInterest',
    'TopicCluster',
    'TopicClusterMember',
    'TopicTrend',
    'TopicExtractionJob',
    'Poll',
    'PollVote',
    'VoteAggregate',
    'UserReputation',
    'VoteFraudDetection',
    'Currency',
    'WalletBalance',
    'WalletSignature',
    'WalletBackupKey',
    'StakingPool',
    'Staking',
    'ExchangeRate',
]